### ISSUE TITLE
void vent constantly full healing

### ISSUE THREAD

**Issue by AimlessRex** [Anreol/VoidQoL#1]
Void vents will heal for all your hp every millisecond with void fields heal enabled

**Comment by Anreol** [comment]
Should be fixed with the latest patch released.

**Comment by AimlessRex** [comment]
Void vents no longer heal repeatedly but now they do not heal at all. Are they supposed to restore you to full health or only partial health?

**Comment by Anreol** [comment]
Partial health, only 75% of your current maximum hp

**Comment by Anreol** [comment]
This is driving me crazy because I also didn't have any mods installed when testing for #3 and it worked just fine.
I don't have dependency on R2API, so if you still have that on, that might be doing something on its own.
Check if you are in the latest BepInEx version release, the previous one was broken as in the mod wasn't even able to initialize.

Next time, if you have any logs, also post them. I'd understand the cell vent not healing, but I'm not modifying the combat director or the void cell themselves in any way, I'm just reading values off them, so no enemies spawning such as in issue #3 doesn't make much sense.

**Comment by AimlessRex** [comment]
[LogOutput.log](https://github.com/Anreol/VoidQoL/files/8216598/LogOutput.log)

https://streamable.com/237t33

**Comment by Anreol** [comment]
Should also be fixed with the latest update.
