### ISSUE TITLE
config options not working

### ISSUE THREAD

**Issue by AimlessRex** [Anreol/VoidQoL#4]
for "Enemy Haste" option are they berserked like before? I couldn't notice any difference in enemies speed or appearance.

for "zone auto charge" for the default 0 should the zone not be charging at all when players are inside it? and only be charging when players get kills in the zone? changing this value from 0 to 4 made no noticeable difference.

for "Zone shape" zones were always sphere same as always with this option enabled and disabled.

for "Zone size increase" changing it from 5 to 20 did not make the zones any larger or smaller.

[LogOutput.log](https://github.com/Anreol/VoidQoL/files/8281619/LogOutput.log)

**Comment by Anreol** [comment]
Checked the log and you only went to void fields. The latest update had all the new config options for Void Locus only, with exception of the enemy haste (Cloak speed boost buff) whenever they spawn being a Void Fields config.
Acid Larvas spawned as a enemy, and since they are pretty fast on their own already, they get like 1-2 seconds of the speed boost buff. If something else like Alloy Vulture or Golems spawn, those get a way longer buff duration.

**Comment by Anreol** [comment]
Closing as I'm assuming it was just a misunderstanding with the Void Locus options and there's nothing broken with it.
